sfdx/force-app/main/default/objects/Monthly_Tracker__c/Monthly_Tracker__c.object-meta.xml
<CustomObject>
    <label>Monthly Tracker</label>
    <nameField>
        <displayFormat>MT-{00000}</displayFormat>
        <label>Monthly Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Bonus__c.field-meta.xml
<CustomField>
    <fullName>Bonus__c</fullName>
    <label>Bonus</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Bonus</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Bonus_Projected__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Projected__c</fullName>
    <label>Bonus Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CapitalGain__c.field-meta.xml
<CustomField>
    <fullName>CapitalGain__c</fullName>
    <label>Capital Gain</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Capital Gain</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CapitalGain_Projected__c.field-meta.xml
<CustomField>
    <fullName>CapitalGain_Projected__c</fullName>
    <label>Capital Gain Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Cook__c.field-meta.xml
<CustomField>
    <fullName>Cook__c</fullName>
    <label>Cook</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Cook</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Cook_Projected__c.field-meta.xml
<CustomField>
    <fullName>Cook_Projected__c</fullName>
    <label>Cook Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CreditCardBillPayment__c.field-meta.xml
<CustomField>
    <fullName>CreditCardBillPayment__c</fullName>
    <label>Credit Card Bill Payment</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Credit Card Bill Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CreditCardBillPayment_Projected__c.field-meta.xml
<CustomField>
    <fullName>CreditCardBillPayment_Projected__c</fullName>
    <label>Credit Card Bill Payment Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Food__c.field-meta.xml
<CustomField>
    <fullName>Food__c</fullName>
    <label>Food</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Food</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Food_Projected__c.field-meta.xml
<CustomField>
    <fullName>Food_Projected__c</fullName>
    <label>Food Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Fuel__c.field-meta.xml
<CustomField>
    <fullName>Fuel__c</fullName>
    <label>Fuel</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Fuel</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Fuel_Projected__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Projected__c</fullName>
    <label>Fuel Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/GiftGiven__c.field-meta.xml
<CustomField>
    <fullName>GiftGiven__c</fullName>
    <label>Gift Given</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Expense</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Gift</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/GiftGiven_Projected__c.field-meta.xml
<CustomField>
    <fullName>GiftGiven_Projected__c</fullName>
    <label>Gift Given Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/GiftReceived__c.field-meta.xml
<CustomField>
    <fullName>GiftReceived__c</fullName>
    <label>Gift Received</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Transaction_Type__c</field>
        <operation>equals</operation>
        <value>Income</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Gift</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Groceries__c.field-meta.xml
<CustomField>
    <fullName>Groceries__c</fullName>
    <label>Groceries</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Groceries</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/HouseBills__c.field-meta.xml
<CustomField>
    <fullName>HouseBills__c</fullName>
    <label>House Bills</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>House Bills</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/InternetBill__c.field-meta.xml
<CustomField>
    <fullName>InternetBill__c</fullName>
    <label>Internet Bill</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Internet Bill</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Loan</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Maid__c.field-meta.xml
<CustomField>
    <fullName>Maid__c</fullName>
    <label>Maid</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Maid</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/MedicalBill__c.field-meta.xml
<CustomField>
    <fullName>MedicalBill__c</fullName>
    <label>Medical Bill</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Medical Bill</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Misc__c.field-meta.xml
<CustomField>
    <fullName>Misc__c</fullName>
    <label>Misc</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Misc</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Others__c.field-meta.xml
<CustomField>
    <fullName>Others__c</fullName>
    <label>Others</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Others</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Paycheck__c.field-meta.xml
<CustomField>
    <fullName>Paycheck__c</fullName>
    <label>Paycheck</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Paycheck</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Refund__c.field-meta.xml
<CustomField>
    <fullName>Refund__c</fullName>
    <label>Refund</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Refund</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Savings__c.field-meta.xml
<CustomField>
    <fullName>Savings__c</fullName>
    <label>Savings</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Savings</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Travel__c.field-meta.xml
<CustomField>
    <fullName>Travel__c</fullName>
    <label>Travel</label>
    <summarizedField>Financial_Transaction__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Financial_Transaction__c.Category__c</field>
        <operation>equals</operation>
        <value>Travel</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Transaction__c.Monthly_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx/force-app/main/default/classes/MonthlyTrackerSelector.cls
public with sharing class MonthlyTrackerSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType() {
        return Monthly_Tracker__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Monthly_Tracker__c.Id,
            Monthly_Tracker__c.Month__c,
            Monthly_Tracker__c.Year__c,
            Monthly_Tracker__c.Bonus__c,
            Monthly_Tracker__c.CapitalGain__c,
            Monthly_Tracker__c.Cook__c,
            Monthly_Tracker__c.CreditCardBillPayment__c,
            Monthly_Tracker__c.Food__c,
            Monthly_Tracker__c.Fuel__c,
            Monthly_Tracker__c.GiftGiven__c,
            Monthly_Tracker__c.GiftReceived__c,
            Monthly_Tracker__c.Groceries__c,
            Monthly_Tracker__c.HouseBills__c,
            Monthly_Tracker__c.Interest__c,
            Monthly_Tracker__c.InternetBill__c,
            Monthly_Tracker__c.Loan__c,
            Monthly_Tracker__c.Maid__c,
            Monthly_Tracker__c.MedicalBill__c,
            Monthly_Tracker__c.Misc__c,
            Monthly_Tracker__c.Others__c,
            Monthly_Tracker__c.Paycheck__c,
            Monthly_Tracker__c.Refund__c,
            Monthly_Tracker__c.Savings__c,
            Monthly_Tracker__c.Travel__c,
            Monthly_Tracker__c.Bonus_Projected__c,
            Monthly_Tracker__c.CapitalGain_Projected__c,
            Monthly_Tracker__c.Cook_Projected__c,
            Monthly_Tracker__c.CreditCardBillPayment_Projected__c,
            Monthly_Tracker__c.Food_Projected__c,
            Monthly_Tracker__c.Fuel_Projected__c,
            Monthly_Tracker__c.GiftGiven_Projected__c,
            Monthly_Tracker__c.GiftReceived_Projected__c,
            Monthly_Tracker__c.Groceries_Projected__c,
            Monthly_Tracker__c.HouseBills_Projected__c,
            Monthly_Tracker__c.Interest_Projected__c,
            Monthly_Tracker__c.InternetBill_Projected__c,
            Monthly_Tracker__c.Loan_Projected__c,
            Monthly_Tracker__c.Maid_Projected__c,
            Monthly_Tracker__c.MedicalBill_Projected__c,
            Monthly_Tracker__c.Misc_Projected__c,
            Monthly_Tracker__c.Others_Projected__c,
            Monthly_Tracker__c.Paycheck_Projected__c,
            Monthly_Tracker__c.Refund_Projected__c,
            Monthly_Tracker__c.Savings_Projected__c,
            Monthly_Tracker__c.Travel_Projected__c,
            Monthly_Tracker__c.TotalExpense__c,
            Monthly_Tracker__c.TotalIncome__c
        };
    }

    public Monthly_Tracker__c getTrackerRecord(String month, String year) {

        return (Monthly_Tracker__c) Database.query(
            newQueryFactory()
                .setCondition(
                    'Month__c =:month ' + 
                    'AND Year__c =:year'
                )
                .toSOQL()
        );

    }

}