sfdx/force-app/main/default/objects/Credit_Card__c/Credit_Card__c.object-meta.xml
<CustomObject>
    <description>This Custom object stores all the Credit Card details</description>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Amount_Utilised__c.field-meta.xml
<CustomField>
    <fullName>Amount_Utilised__c</fullName>
    <description>To store the credit limit utilised for use</description>
    <inlineHelpText>Credit Utilised</inlineHelpText>
    <label>Amount Utilised</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Available_Limit__c.field-meta.xml
<CustomField>
    <fullName>Available_Limit__c</fullName>
    <description>To display the available credit limit that can be utilised</description>
    <formula>Total_Limit__c - Amount_Utilised__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Available Credit Limit</inlineHelpText>
    <label>Available Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Credit_Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Name__c</fullName>
    <description>To store the name of the Credit card</description>
    <inlineHelpText>Name of the Credit Card</inlineHelpText>
    <label>Credit Card Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Total_Limit__c.field-meta.xml
<CustomField>
    <fullName>Total_Limit__c</fullName>
    <description>To store the total credit limit permissible for the credit card issued</description>
    <inlineHelpText>Total limit of the Credit Card</inlineHelpText>
    <label>Total Limit</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/classes/CreditCardSelector.cls
public with sharing class CreditCardSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType() {
        return Credit_Card__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Credit_Card__c.Id,
            Credit_Card__c.Credit_Card_Name__c,
            Credit_Card__c.Amount_Utilised__c,
            Credit_Card__c.Available_Limit__c,
            Credit_Card__c.Total_Limit__c
        };
    }

    public List<Credit_Card__c> getCreditCards() {
        return (List<Credit_Card__c>) Database.query(
            newQueryFactory()
                .toSOQL()
        );
    }

    public Credit_Card__c getCreditCardById(Id recordId) {
        return (Credit_Card__c) Database.query(
            newQueryFactory()
                .setCondition('Id =:recordId')
                .toSOQL()
        );
    }

}