sfdx/force-app/main/default/objects/Credit_Card__c/Credit_Card__c.object-meta.xml
<CustomObject>
    <description>This Custom object stores all the Credit Card details</description>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Amount_Utilised__c.field-meta.xml
<CustomField>
    <fullName>Amount_Utilised__c</fullName>
    <description>To store the credit limit utilised for use</description>
    <inlineHelpText>Credit Utilised</inlineHelpText>
    <label>Amount Utilised</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Credit_Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Name__c</fullName>
    <description>To store the name of the Credit card</description>
    <inlineHelpText>Name of the Credit Card</inlineHelpText>
    <label>Credit Card Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/Financial_Transaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TransactionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument_Detail__c</fullName>
    <label>Payment Instrument Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/CreditCardPaymentProcessor.cls
public without sharing class CreditCardPaymentProcessor implements PaymentProcessor {
    
    private Map<String, Credit_Card__c> cardMap;
    
    /**
     * @name        : CreditCardPaymentProcessor (Constructor)
     * @param       : null
     * @return      : null
     * @description : constructor method
     */
    public CreditCardPaymentProcessor() {

        // Initialising the Card Map
        this.cardMap = new Map<String, Credit_Card__c>();
        // Querying the Credit Card data
        fflib_QueryFactory query = new fflib_QueryFactory(Credit_Card__c.SObjectType);
        query.selectField(Credit_Card__c.Id)
        .selectField(Credit_Card__c.Credit_Card_Name__c)
        .selectField(Credit_Card__c.Amount_Utilised__c);
        
        for(Credit_Card__c card : Database.query(query.toSOQL())) {
            this.cardMap.put(card.Credit_Card_Name__c, card);
        }

    }

    /**
     * @name        : recordInsertion
     * @param       : txnRecords => List of Financial_Transaction__c to be processed
     *                insertFlag => true for insert, false for delete
     * @return      : null
     * @description : Method that processes the record Insertion if the payment method is Credit Card
     */
    public void recordInsertion(List<Financial_Transaction__c> txnRecords, boolean insertFlag) {

        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<Schema.SObjectType> {
                Credit_Card__c.SObjectType
            }
        );

        for(Financial_Transaction__c txn : txnRecords) {
            Credit_Card__c card = cardMap.get(txn.Payment_Instrument_Detail__c);
            try{
                Decimal amt = (txn.Amount__c == null) ? 0 : txn.Amount__c;
                // Preserve previous intended sign: insert -> increase the utilisation, else -> decrease
                card.Amount_Utilised__c = card.Amount_Utilised__c + (insertFlag ? amt : -amt);
                uow.registerDirty(card);
            }
            catch(Exception e) {}
        }
        uow.commitWork();

    }

}