sfdx/force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the bank account details</description>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Minimum_Balance__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Balance__c</fullName>
    <label>Minimum Balance</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Savings Account</fullName>
        <default>true</default>
        <label>Savings Account</label>
    </customValue>
    <customValue>
        <fullName>Joint Account</fullName>
    </customValue>
    <description>Picklist value for the type of account</description>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/classes/BankAccountSelector.cls
public with sharing class BankAccountSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType() {
        return Bank_Account__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Bank_Account__c.Id,
            Bank_Account__c.Name,
            Bank_Account__c.Bank_Account_Name__c,
            Bank_Account__c.Account_Type__c,
            Bank_Account__c.Balance__c,
            Bank_Account__c.Minimum_Balance__c
        };
    }

    public List<Bank_Account__c> getBankAccounts() {
        return (List<Bank_Account__c>) Database.query(
            newQueryFactory()
                .toSOQL()
        );
    }

    public Bank_Account__c getBankAccountById(Id recordId) {
        return (Bank_Account__c) Database.query(
            newQueryFactory()
            .setCondition('Id =:recordId')
            .toSOQL()
        );
    }

}