sfdx/force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the bank account details</description>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Bank_Account__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Credit_Card__c/Credit_Card__c.object-meta.xml
<CustomObject>
    <description>This Custom object stores all the Credit Card details</description>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Credit_Card__c/fields/Credit_Card_Name__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Name__c</fullName>
    <description>To store the name of the Credit card</description>
    <inlineHelpText>Name of the Credit Card</inlineHelpText>
    <label>Credit Card Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/Financial_Transaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TransactionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument__c</fullName>
    <label>Payment Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Instrument</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument_Detail__c</fullName>
    <label>Payment Instrument Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/globalValueSets/Account_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Savings Account</fullName>
        <default>true</default>
        <label>Savings Account</label>
    </customValue>
    <customValue>
        <fullName>Joint Account</fullName>
    </customValue>
    <description>Picklist value for the type of account</description>
    <masterLabel>Account Type</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Payment_Instrument.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Joint Account</fullName>
    </customValue>
    <customValue>
        <fullName>Savings Account</fullName>
    </customValue>
    <masterLabel>Payment Instrument</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <description>Picklist values for the type of Payment methods used</description>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/classes/FinancialTransactionService.cls
public with sharing class FinancialTransactionService {
    
    /**
     * @name        : getTransactionRecords
     * @param       : String => Transaction type
     *              : Integer => Contains the month value
     *              : Integer => Contains the year value
     * @return      : List<Financial_Transaction__c> => List of Financial_Transaction__c records based on the parameters passed
     * @description : method to fetch the Financial_Transaction__c records
     */
    public static List<Financial_Transaction__c> getTransactionRecords(String txnType, Integer month, Integer year) {

        FinancialTransactionSelector selector = new FinancialTransactionSelector();
        return selector.getRecordsByTxnType(txnType, month, year);

    }
    
    /**
     * @name        : getTransactionRecordById
     * @param       : Id => record id of the Financial_Transaction__c
     * @return      : Financial_Transaction__c => Financial_Transaction__c record based on the record id parameter passed
     * @description : method to fetch the Financial_Transaction__c record
     */
    public static Financial_Transaction__c getTransactionRecordById(Id recordId) {

        FinancialTransactionSelector selector = new FinancialTransactionSelector();
        return selector.getTransactionRecordById(recordId);

    }

    /**
     * @name        : updateRecord
     * @param       : Financial_Transaction__c => Financial_Transaction__c record that needs to be updated
     * @return      : String => returns Successful on updation of the record, otherwise Failed
     * @description : method to update the Financial_Transaction__c record
     */
    public static String updateRecord(Financial_Transaction__c txn) {

        // Create a Unit Of Work
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Financial_Transaction__c.SObjectType
            }
        );
        uow.registerDirty(txn);
        String successFlag = 'Successful';
        try {
            // Commit the work
            uow.commitWork();
        }
        catch(Exception e) {
            successFlag = 'Failed';
        }
        return successFlag;

    }

    /**
     * @name        : PickListValueClass
     * @description : Wrapper class to contain the 
     *                Payment_Method__c => Payment_Instrument__c => Payment_Instrument_Detail__c 
     *                picklist value
     */
    public class PickListValueClass {
        List<PaymentMethod> records;
    }
    public class PaymentMethod {
        String paymentMethod;
        List<PaymentInstrument> paymentInstrument;
    }
    public class PaymentInstrument {
        String paymentInstrument;
        List<String> paymentInstrumentDetail;
    }

    /**
     * @name        : getPaymentMethodDependentOptions
     * @param       : null
     * @return      : String => returns json string of the PickListValueClass wrapper class
     *                          containing the Payment_Method__c => Payment_Instrument__c => Payment_Instrument_Detail__c 
     *                          picklist value
     * @description : method to fetch the Payment_Method__c => Payment_Instrument__c => Payment_Instrument_Detail__c 
     *                picklist value
     */
    public static String getPaymentMethodDependentOptions() {

        // Initialise the list PaymentMethod
        List<PaymentMethod> paymentMethods = new List<PaymentMethod>();
        // Describe the field
        Schema.DescribeFieldResult fieldResult = Financial_Transaction__c.Payment_Method__c.getDescribe();
        // Create the PaymentMethod picklist
        for(Schema.PicklistEntry pe : fieldResult.getPicklistValues()) {
            PaymentMethod pm = new PaymentMethod();
            pm.paymentMethod = pe.getLabel();
            paymentMethods.add(pm);
        }
        for(PaymentMethod pm : paymentMethods) {
            // For Cash
            if(pm.paymentMethod == 'Cash'){
                PaymentInstrument pi = new PaymentInstrument();
                pi.paymentInstrument = 'Cash';
                pi.paymentInstrumentDetail = new List<String>{'Cash'};
                
                List<PaymentInstrument> piList = new List<PaymentInstrument>();
                piList.add(pi);
                
                pm.paymentInstrument = piList;
            }
            // For Credit Card
            else if(pm.paymentMethod == 'Credit Card'){
                PaymentInstrument pi = new PaymentInstrument();
                pi.paymentInstrument = 'Credit Card';
                pi.paymentInstrumentDetail = getCreditCards();
                
                List<PaymentInstrument> piList = new List<PaymentInstrument>();
                piList.add(pi);
                
                pm.paymentInstrument = piList;
            }
            // For Online
            else {
                PaymentInstrument pi1 = new PaymentInstrument();
                pi1.paymentInstrument = 'Joint Account';
                pi1.paymentInstrumentDetail = getBankAccounts('Joint Account');
                
                PaymentInstrument pi2 = new PaymentInstrument();
                pi2.paymentInstrument = 'Savings Account';
                pi2.paymentInstrumentDetail = new List<String>();
                pi2.paymentInstrumentDetail = getBankAccounts('Savings Account');
                
                List<PaymentInstrument> piList = new List<PaymentInstrument>();
                piList.add(pi1);
                piList.add(pi2);

                pm.paymentInstrument = piList;
            }
        }
        PickListValueClass pvc = new PickListValueClass();
        pvc.records = paymentMethods;
        String jsonString = JSON.serialize(pvc);
        return jsonString;

    }

    /**
     * @name        : getCreditCards
     * @param       : null
     * @return      : List<String> => returns list of credit card names
     * @description : method to fetch the credit card names
     */
    private static List<String> getCreditCards() {

        // Create a List of String for result
        List<String> result = new List<String>();
        // Query the Credit Cards using the CreditCardSelector
        CreditCardSelector selector = new CreditCardSelector();
        for(Credit_Card__c card : selector.getCreditCards()) {
            result.add(card.Credit_Card_Name__c);
        }
        return result;

    }

    /**
     * @name        : getBankAccounts
     * @param       : null
     * @return      : List<String> => returns list of Bank account names
     * @description : method to fetch the bank account names
     */
    private static List<String> getBankAccounts(String acctType) {

        // Create a List of String for result
        List<String> result = new List<String>();
        // Query the Bank Accounts using the BankAccountSelector
        BankAccountSelector selector = new BankAccountSelector();
        for(Bank_Account__c bankAccount : selector.getBankAccounts()) {
            if(bankAccount.Account_Type__c == acctType){
                String val = bankAccount.Bank_Account_Name__c + ' - ' + bankAccount.Account_Type__c;
                result.add(val);
            }
        }
        return result;

    }

    /**
     * @name        : createRecords
     * @param       : List<Financial_Transaction__c> => List of transaction records
     * @return      : String => returns success on creation of the record, otherwise error
     * @description : method to create the transaction records provided
     */
    public static String createRecords(List<Financial_Transaction__c> txnRecords) {

        String successFlag = 'success';

        // Create a Unit Of Work
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Financial_Transaction__c.SObjectType
            }
        );
        uow.registerNew(txnRecords);
        try {
            // Commit the work
            uow.commitWork();
        }
        catch(Exception e) {
            successFlag = 'error';
        }
        return successFlag;

    }
    
}