sfdx/force-app/main/default/objects/Financial_Transaction__c/Financial_Transaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TransactionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Transaction_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument__c</fullName>
    <label>Payment Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Instrument</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument_Detail__c</fullName>
    <label>Payment Instrument Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Paycheck</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus</fullName>
    </customValue>
    <customValue>
        <fullName>Refund</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Capital Gain</fullName>
    </customValue>
    <customValue>
        <fullName>Interest</fullName>
    </customValue>
    <customValue>
        <fullName>Cook</fullName>
    </customValue>
    <customValue>
        <fullName>Maid</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card Bill Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel</fullName>
    </customValue>
    <customValue>
        <fullName>Groceries</fullName>
    </customValue>
    <customValue>
        <fullName>House Bills</fullName>
    </customValue>
    <customValue>
        <fullName>Misc</fullName>
    </customValue>
    <customValue>
        <fullName>Internet Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Gift</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Savings</fullName>
    </customValue>
    <description>Picklist values for the category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Payment_Instrument.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Joint Account</fullName>
    </customValue>
    <customValue>
        <fullName>Savings Account</fullName>
    </customValue>
    <masterLabel>Payment Instrument</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <description>Picklist values for the type of Payment methods used</description>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Transaction_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Income</fullName>
    </customValue>
    <customValue>
        <fullName>Expense</fullName>
    </customValue>
    <customValue>
        <fullName>Savings</fullName>
    </customValue>
    <description>Picklist value for the type of transaction</description>
    <masterLabel>Transaction Type</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/classes/FinancialTransactionSelector.cls
public with sharing class FinancialTransactionSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType() {
        return Financial_Transaction__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Financial_Transaction__c.Id,
            Financial_Transaction__c.Amount__c,
            Financial_Transaction__c.Description__c,
            Financial_Transaction__c.Payment_Instrument_Detail__c,
            Financial_Transaction__c.Payment_Instrument__c,
            Financial_Transaction__c.Payment_Method__c,
            Financial_Transaction__c.Transaction_Date__c,
            Financial_Transaction__c.Transaction_Type__c,
            Financial_Transaction__c.Category__c
        };
    }

    public List<Financial_Transaction__c> getRecordsByTxnType(String txnType, Integer month, Integer year) {

        return (List<Financial_Transaction__c>) Database.query(
            newQueryFactory()
                .setCondition(
                    'Transaction_Type__c =:txnType ' + 
                    'AND CALENDAR_MONTH(Transaction_Date__c) =:month ' +
                    'AND CALENDAR_YEAR(Transaction_Date__c) =:year'
                )
                .addOrdering('Transaction_Date__c', fflib_QueryFactory.SortOrder.DESCENDING)
                .addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING)
                .toSOQL()
        );

    }

    public Financial_Transaction__c getTransactionRecordById(Id recordId) {

        return (Financial_Transaction__c) Database.query(
            newQueryFactory()
                .setCondition(
                    'Id =:recordId'
                )
                .toSOQL()
        );

    }
    
}