sfdx/force-app/main/default/objects/Financial_Transaction__c/Financial_Transaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TransactionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Monthly_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Tracker__c</fullName>
    <label>Monthly Tracker</label>
    <referenceTo>Monthly_Tracker__c</referenceTo>
    <relationshipLabel>Financial Transactions</relationshipLabel>
    <relationshipName>Financial_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/Monthly_Tracker__c.object-meta.xml
<CustomObject>
    <label>Monthly Tracker</label>
    <nameField>
        <displayFormat>MT-{00000}</displayFormat>
        <label>Monthly Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Bonus_Projected__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Projected__c</fullName>
    <label>Bonus Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CapitalGain_Projected__c.field-meta.xml
<CustomField>
    <fullName>CapitalGain_Projected__c</fullName>
    <label>Capital Gain Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Cook_Projected__c.field-meta.xml
<CustomField>
    <fullName>Cook_Projected__c</fullName>
    <label>Cook Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/CreditCardBillPayment_Projected__c.field-meta.xml
<CustomField>
    <fullName>CreditCardBillPayment_Projected__c</fullName>
    <label>Credit Card Bill Payment Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Food_Projected__c.field-meta.xml
<CustomField>
    <fullName>Food_Projected__c</fullName>
    <label>Food Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Fuel_Projected__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Projected__c</fullName>
    <label>Fuel Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/GiftGiven_Projected__c.field-meta.xml
<CustomField>
    <fullName>GiftGiven_Projected__c</fullName>
    <label>Gift Given Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/GiftReceived_Projected__c.field-meta.xml
<CustomField>
    <fullName>GiftReceived_Projected__c</fullName>
    <label>Gift Received Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Groceries_Projected__c.field-meta.xml
<CustomField>
    <fullName>Groceries_Projected__c</fullName>
    <label>Groceries Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/HouseBills_Projected__c.field-meta.xml
<CustomField>
    <fullName>HouseBills_Projected__c</fullName>
    <label>House Bills Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Interest_Projected__c.field-meta.xml
<CustomField>
    <fullName>Interest_Projected__c</fullName>
    <label>Interest Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/InternetBill_Projected__c.field-meta.xml
<CustomField>
    <fullName>InternetBill_Projected__c</fullName>
    <label>Internet Bill Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Loan_Projected__c.field-meta.xml
<CustomField>
    <fullName>Loan_Projected__c</fullName>
    <label>Loan Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Maid_Projected__c.field-meta.xml
<CustomField>
    <fullName>Maid_Projected__c</fullName>
    <label>Maid Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/MedicalBill_Projected__c.field-meta.xml
<CustomField>
    <fullName>MedicalBill_Projected__c</fullName>
    <label>Medical Bill Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Misc_Projected__c.field-meta.xml
<CustomField>
    <fullName>Misc_Projected__c</fullName>
    <label>Misc Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Others_Projected__c.field-meta.xml
<CustomField>
    <fullName>Others_Projected__c</fullName>
    <label>Others Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Paycheck_Projected__c.field-meta.xml
<CustomField>
    <fullName>Paycheck_Projected__c</fullName>
    <label>Paycheck Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Refund_Projected__c.field-meta.xml
<CustomField>
    <fullName>Refund_Projected__c</fullName>
    <label>Refund Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Savings_Projected__c.field-meta.xml
<CustomField>
    <fullName>Savings_Projected__c</fullName>
    <label>Savings Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Monthly_Tracker__c/fields/Travel_Projected__c.field-meta.xml
<CustomField>
    <fullName>Travel_Projected__c</fullName>
    <label>Travel Projected</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <description>Picklist values for the type of Payment methods used</description>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/classes/FinancialTransactionHelper.cls
public with sharing class FinancialTransactionHelper {
    
    public static Map<String, Monthly_Tracker__c> prepareTrackerMap() {

        // result Map
        Map<String, Monthly_Tracker__c> resultMap = new Map<String, Monthly_Tracker__c>();
        // Querying the data
        fflib_QueryFactory query = new fflib_QueryFactory(Monthly_Tracker__c.SObjectType);
        query.selectField(Monthly_Tracker__c.Id)
        .selectField(Monthly_Tracker__c.Month__c)
        .selectField(Monthly_Tracker__c.Year__c);
        for(Monthly_Tracker__c tracker : Database.query(query.toSOQL())) {
            resultMap.put(tracker.Month__c+'-'+tracker.Year__c, tracker);
        }
        return resultMap;

    }

    // method to checking the need to create a new Monthly_Tracker__c record
    public static List<Monthly_Tracker__c> checkTrackersForCreation(List<Financial_Transaction__c> newTransactionRecords, Map<String, Monthly_Tracker__c> trackerMap) {

        String month;
        String year;
        List<Monthly_Tracker__c> trackersToBeCreated = new List<Monthly_Tracker__c>();
        
        for(Financial_Transaction__c record : newTransactionRecords) {
            month = Datetime.newInstance(record.Transaction_Date__c, Time.newInstance(0, 0, 0, 0)).format('MMMM');
            year = record.Transaction_Date__c.year().toString();
            String key = month+'-'+year;
            if(!trackerMap.containsKey(key)) {
                Monthly_Tracker__c newTracker = new Monthly_Tracker__c(
                    Month__c = month,
                    Year__c = year,
                    Bonus_Projected__c = 0,
                    CapitalGain_Projected__c = 0,
                    Cook_Projected__c = 0,
                    CreditCardBillPayment_Projected__c = 0,
                    Food_Projected__c = 0,
                    Fuel_Projected__c = 0,
                    GiftGiven_Projected__c = 0,
                    GiftReceived_Projected__c = 0,
                    Groceries_Projected__c = 0,
                    HouseBills_Projected__c = 0,
                    Interest_Projected__c = 0,
                    InternetBill_Projected__c = 0,
                    Loan_Projected__c = 0,
                    Maid_Projected__c = 0,
                    MedicalBill_Projected__c = 0,
                    Misc_Projected__c = 0,
                    Others_Projected__c = 0,
                    Paycheck_Projected__c = 0,
                    Refund_Projected__c = 0,
                    Savings_Projected__c = 0,
                    Travel_Projected__c = 0
                );
                trackerMap.put(key, newTracker);
                trackersToBeCreated.add(newTracker);
            }
        }
        return trackersToBeCreated;

    }

    // method to create the tracker records
    public static List<Monthly_Tracker__c> createTrackers(List<Monthly_Tracker__c> trackersToBeCreated) {

        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<Schema.SObjectType> {
                Monthly_Tracker__c.SObjectType
            }
        );
        uow.registerNew(trackersToBeCreated);
        uow.commitWork();
        return trackersToBeCreated;

    }

    // method to map Monthly_Tracker__c to Financial_Transaction__c records
    public static void mapTrackerToRecords(List<Financial_Transaction__c> newTransactionRecords, Map<String, Monthly_Tracker__c> trackerMap) {
        
        String month;
        String year;
        List<Monthly_Tracker__c> trackerRecords = checkTrackersForCreation(newTransactionRecords, trackerMap);

        if(trackerRecords != null && trackerRecords.size() != 0) {
            createTrackers(trackerRecords);
            trackerMap = prepareTrackerMap();
        }
       try {
            for(Financial_Transaction__c record : newTransactionRecords) {
                month = Datetime.newInstance(record.Transaction_Date__c, Time.newInstance(0, 0, 0, 0)).format('MMMM');
                year = record.Transaction_Date__c.year().toString();
                String key = month+'-'+year;
                record.Monthly_Tracker__c = trackerMap.get(key).Id;
            }
        }
        catch(Exception e) {
            System.debug('Issue with the tracker record insertion.Please review the issue!');
        }

    }

    // method to create the Payment Map
    public static Map<String, List<Financial_Transaction__c>> createPaymentTypeMap(List<Financial_Transaction__c> txnRecords) {

        Map<String, List<Financial_Transaction__c>> paymentTypeMap = new Map<String, List<Financial_Transaction__c>>();
        // Group records by payment type
        for(Financial_Transaction__c txn : txnRecords) {
            if(!paymentTypeMap.containsKey(txn.Payment_Method__c)){
                paymentTypeMap.put(txn.Payment_Method__c, new List<Financial_Transaction__c>());
            }
            paymentTypeMap.get(txn.Payment_Method__c).add(txn);
        }
        return paymentTypeMap;

    }
    
}