sfdx/force-app/main/default/objects/Financial_Transaction__c/Financial_Transaction__c.object-meta.xml
<CustomObject>
    <label>Financial Transaction</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>TransactionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument__c</fullName>
    <label>Payment Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Instrument</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Instrument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Payment_Instrument_Detail__c</fullName>
    <label>Payment Instrument Detail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Financial_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Methods</valueSetName>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/globalValueSets/Payment_Instrument.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Joint Account</fullName>
    </customValue>
    <customValue>
        <fullName>Savings Account</fullName>
    </customValue>
    <masterLabel>Payment Instrument</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/globalValueSets/Payment_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <description>Picklist values for the type of Payment methods used</description>
    <masterLabel>Payment Methods</masterLabel>
</GlobalValueSet>

sfdx/force-app/main/default/classes/FinancialTransactionsPageController.cls
public with sharing class FinancialTransactionsPageController {

    /**
     * @name        : getTxnRecords
     * @param       : String => Transaction type
     *              : Integer => Contains the month value
     *              : Integer => Contains the year value
     * @return      : List<Financial_Transaction__c> => List of Financial_Transaction__c records based on the parameters passed
     * @description : method to fetch the Financial_Transaction__c records
     */
    @AuraEnabled
    public static List<Financial_Transaction__c> getTxnRecords(String txnType, Integer month, Integer year){
        return FinancialTransactionService.getTransactionRecords(txnType, month, year);
    }

    /**
     * @name        : getTxnRecordById
     * @param       : Id => record id of the Financial_Transaction__c
     * @return      : Financial_Transaction__c => Financial_Transaction__c record based on the record id parameter passed
     * @description : method to fetch the Financial_Transaction__c record
     */
    @AuraEnabled
    public static Financial_Transaction__c getTxnRecordById(Id recordId){
        return FinancialTransactionService.getTransactionRecordById(recordId);
    }

    /**
     * @name        : updateTransaction
     * @param       : Financial_Transaction__c => Financial_Transaction__c record that needs to be updated
     * @return      : String => returns Successful on updation of the record, otherwise Failed
     * @description : method to update the Financial_Transaction__c record
     */
    @AuraEnabled
    public static String updateTransaction(Financial_Transaction__c txn){
        return FinancialTransactionService.updateRecord(txn);
    }

    /**
     * @name        : getPaymentMethodDependentOptions
     * @param       : null
     * @return      : String => returns json string of the PickListValueClass wrapper class
     *                          containing the Payment_Method__c => Payment_Instrument__c => Payment_Instrument_Detail__c 
     *                          picklist value
     * @description : method to fetch the Payment_Method__c => Payment_Instrument__c => Payment_Instrument_Detail__c 
     *                picklist value
     */
    @AuraEnabled(cacheable=true)
    public static String getPaymentMethodDependentOptions(){
        return FinancialTransactionService.getPaymentMethodDependentOptions();
    }

    /**
     * @name        : createRecords
     * @param       : List<Financial_Transaction__c> => List of transaction records
     * @return      : String => returns success on creation of the record, otherwise error
     * @description : method to create the transaction records provided
     */
    @AuraEnabled
    public static string createRecords(List<Financial_Transaction__c> records){
        return FinancialTransactionService.createRecords(records);
    }
    
}